import { Technique } from "./store";

export const techniques = {
  Fire: [
    {
      name: "Fire Bolt",
      onGoing: false,
      active: false,
      aspect: "Fire",
      type: "Range",
      baseCost: 5,
      minCost: 1,
      effect: "damage",
      customEffect: undefined,
      magnitude: 5,
      description: "Fire a small ball of fire at the target",
      mastery: 1,
      multiplier: 1,
    },
    {
      name: "Clense wounds in flame",
      onGoing: false,
      active: false,
      aspect: "Fire",
      type: "Enhancement",
      baseCost: 5,
      minCost: 1,
      effect: "heal",
      customEffect: undefined,
      magnitude: 1,
      description: "Sear your wounds closed",
      mastery: 1,
      multiplier: 1,
    },
  ] as Technique[],
  Water: [
    {
      name: "Water Whip",
      onGoing: false,
      active: false,
      aspect: "Water",
      type: "Range",
      baseCost: 5,
      minCost: 1,
      effect: "damage",
      customEffect: undefined,
      magnitude: 5,
      description: "Send a whip of water at the target",
      mastery: 1,
      multiplier: 1,
    },
  ] as Technique[],
};
